const
  API_URL = 'http://localhost:3000',
  AUTH_USER = 'authUser',
  CREATE_USER = 'createUser',
  LOGOUT = 'logout',
  GET_CURRENT_USER = 'getCurrentUser',
  SET_CURRENT_USER = 'setCurrentUser',
  GET_AUTH_STATUS = 'getAuthStatus',
  SET_AUTH_STATUS = 'setAuthStatus',
  LOAD_ARTISTS = 'loadArtists',
  GET_ARTISTS = 'getArtists',
  SET_ARTISTS = 'setArtists'

export default {
  API_URL: API_URL,
  GET_CURRENT_USER: GET_CURRENT_USER,
  SET_CURRENT_USER: SET_CURRENT_USER,
  GET_AUTH_STATUS: GET_AUTH_STATUS,
  SET_AUTH_STATUS: SET_AUTH_STATUS,
  AUTH_USER: AUTH_USER,
  CREATE_USER: CREATE_USER,
  LOGOUT: LOGOUT,
  LOAD_ARTISTS: LOAD_ARTISTS,
  GET_ARTISTS: GET_ARTISTS,
  SET_ARTISTS: SET_ARTISTS
}
